[theme]
primaryColor = "#5C2D91"  # Roxo ICEV
backgroundColor = "#F2F4F8"  # Cinza claro para fundo suave
secondaryBackgroundColor = "#D9E2F3"  # Azul claro para painéis laterais
textColor = "#212121"  # Preto suave para boa legibilidade
font = "sans serif"
